import { useEffect } from 'react'
import { Check, Dumbbell, Info, Play, X } from 'lucide-react'
import type { WorkoutId } from './types'

const warmups: Record<WorkoutId, { title: string; steps: string[] }> = {
  A: { title: 'Разминка A', steps: ['Беговая дорожка — 5 минут: быстрая ходьба или лёгкий бег.', 'Круговые движения плечами, вращения рук, локтей и кистей — по 8–12 раз.', 'Повороты корпуса, круги тазом и несколько приседаний без веса.', 'Разведения рук с резинкой — 2 × 15–20.', 'Внешняя ротация плеча с резинкой — 1–2 × 12–15.', 'Отжимания — 1 × 10–15, не до отказа.', 'Перед жимом постепенно подними вес: 20 × 15 → 40 × 8 → 55 × 4–5.'] },
  B: { title: 'Разминка B', steps: ['Беговая дорожка — 5 минут: разогрейся, но не утомляйся.', 'Круговые движения плечами, вращения рук, локтей и кистей — по 8–12 раз.', 'Повороты корпуса, круги тазом и несколько приседаний без веса.', 'Разведения резинки — 2 × 15–20.', 'Тяга резинки к груди — 2 × 12–15.', 'Лёгкая тяга верхнего блока — 1 × 15.', 'Первый подход подтягиваний сделай облегчённым, не до отказа.'] },
  C: { title: 'Разминка C', steps: ['Беговая дорожка — 5 минут: быстрая ходьба или лёгкий бег.', 'Круговые движения плечами, вращения рук, локтей и кистей — по 8–12 раз.', 'Повороты корпуса, круги тазом и несколько приседаний без веса.', 'Приседания без веса — 2 × 10.', 'Выпады без веса — 1 × 8 на каждую ногу.', 'Ягодичный мост — 1 × 15.', 'Махи ногой вперёд-назад и в сторону — по 10 каждой ногой.', 'Перед приседом постепенно подними вес: 20 × 12 → 40 × 8 → 60 × 4–5.'] }
}

export function WarmupSheet({ workoutId, onComplete }: { workoutId: WorkoutId; onComplete: () => void }) {
  const warmup = warmups[workoutId]
  useEffect(() => { document.body.classList.add('modal-open'); return () => document.body.classList.remove('modal-open') }, [])
  return <div className="modal-backdrop warmup-backdrop"><section className="warmup-sheet" role="dialog" aria-modal="true" aria-labelledby="warmup-title"><div className="warmup-icon"><Dumbbell size={22} /></div><span className="mini-label">ПЕРЕД ТРЕНИРОВКОЙ {workoutId}</span><h2 id="warmup-title">{warmup.title}</h2><p className="warmup-lead">Подготовь тело, суставы и мышцы. Разминка не должна утомлять.</p><div className="warmup-list">{warmup.steps.map((step, index) => <div className="warmup-step" key={step}><span>{index + 1}</span><p>{step}</p></div>)}</div><div className="warmup-rule"><strong>Главное правило</strong><span>Подними температуру тела и постепенно подведи себя к рабочему весу.</span></div><button className="primary-button wide" onClick={onComplete}><Check size={18} /> Разминка завершена</button></section></div>
}

export function TrainingGuide({ onClose }: { onClose: () => void }) {
  return <div className="modal-backdrop guide-backdrop" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><section className="sheet guide-sheet" role="dialog" aria-modal="true" aria-labelledby="guide-title"><button className="icon-button close-button" onClick={onClose} aria-label="Закрыть"><X /></button><span className="mini-label"><Info size={14} /> ГАЙД</span><h2 id="guide-title">Как прогрессировать</h2><div className="guide-section"><h3>Как подбирать вес</h3><p>Заканчивай большинство рабочих подходов с 1–3 повторениями в запасе (RIR). Если в формате 3 × 8–12 получается 12 / 12 / 12 с хорошей техникой, немного увеличь вес. Не нужно каждый подход делать до абсолютного отказа.</p></div><div className="guide-section"><h3>Прогресс на 4 недели</h3><p><b>Неделя 1:</b> подбери рабочие веса и отточи технику.<br /><b>Неделя 2:</b> добавь суммарно 1–2 повторения.<br /><b>Неделя 3:</b> повысь вес там, где достиг верхней границы.<br /><b>Неделя 4:</b> продолжай прогрессию или снизь объём на 20–30% при сильной усталости.</p><p>Записывай веса и повторения, чтобы видеть реальный прогресс.</p></div><div className="guide-section"><h3>Чтобы появился рельеф</h3><p>Начни с небольшого дефицита калорий. Белок: 1,6–2,0 г/кг, ориентировочно 110–140 г в сутки. Спи 7–9 часов и оценивай вес по среднему значению за неделю.</p></div></section></div>
}
